source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'
workspace 'e-conomic-demo-workspace'
link_with 'e-conomic-demo', 'e-conomic-demoTests'
xcodeproj 'e-conomic-demo'

pod 'ObjectiveSugar'
pod 'AFNetworking'
pod 'Objection'
pod 'MagicalRecord'
pod 'CocoaLumberjack'
pod 'Bolts'
pod 'IQKeyboardManager'
pod 'UIViewController+KeyboardAnimation', '~> 1.2'
pod 'RMDateSelectionViewController', '~> 2.0.1'